services:
  instivo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instivo-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - instivo-mongodb

  instivo-mongodb:
    image: mongo:8.0.0
    container_name: instivo-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: instivo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
