services:
  instivo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instivo-api
    restart: always
    depends_on:
      - instivo-mongodb
    networks:
      - instivo-network
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:admin@instivo-mongodb:27017/instivo?authSource=admin

  instivo-mongodb:
    image: mongo:8.0.0
    container_name: instivo-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: instivo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - instivo-network

volumes:
  mongodb_data:

networks:
  instivo-network:
    driver: bridge
